### ISSUE TITLE
Question of Pretraining on RefCOCO/+/g train/val.json

### ISSUE THREAD

**Issue by yrlcoco** [wjn922/ReferFormer#10]
Hi! So glad that you released the pretrain code on Refcoco Datasets.
And, in [datasets/refexp.py](https://github.com/wjn922/ReferFormer/blob/main/datasets/refexp.py) Line 168/169, you divided original json files into train/val splits.
However, I download json files on [refer](https://github.com/lichengunc/refer). They use many different mode like 'unc', 'berkeley','google'.
So, could you please share your json files of RefCOCO/+/g train/val.json?

Thanks a lot!

**Comment by wjn922** [comment]
Hi，

We have provided the data conversion file [tools/data/convert_refexp_to_coco.py](https://github.com/wjn922/ReferFormer/blob/main/tools/data/convert_refexp_to_coco.py) for converting the refcoco annotation files to coco json format.
And they can be processed by the dataloader in datasets/refexp.py.

**Comment by yrlcoco** [comment]
thank  you~
