### ISSUE TITLE
How to use CFBI as post-process

### ISSUE THREAD

**Issue by Zhiweihhh** [wjn922/ReferFormer#12]
I saw you are using CFBI as post-process, could you provide more implementation details of your algorithm? For example, are all of the predicted results involved in post-processing, and how are they loaded into the CFBI?

**Comment by wjn922** [comment]
Hi,

For the CFBI post-process, we choose the frame with the highest score as the key frame, and then uses CFBI to propogate it forward and backward to the entire video frames. The process is complicated which includes the inference of ReferFormer and CFBI.

If you want to do the post-process, you need to make some modifications for the original CFBI dataloader https://github.com/z-x-yang/CFBI/blob/master/dataloaders/datasets.py.
