### ISSUE TITLE
Codes about pre-training process

### ISSUE THREAD

**Issue by yzleroy** [wjn922/ReferFormer#2]
Could you release your codes for data pre-processing, especially for RefCOCO, RefCOCO+ and RefCOCOg ?

**Comment by wjn922** [comment]
Hi @yzleroy,

Currently, we do not have the plan to release the pre-train code. But we may release it at some point in the future.

Generally, the pre-processed RefCOCO/+/g annotation files are in the COCO format, very similar to those provided by [MDETR](https://github.com/ashkamath/mdetr/blob/main/.github/refexp.md).

In this repository, we have provided the dataloader for loading these referring datasets, see [here](https://github.com/wjn922/ReferFormer/blob/main/datasets/refexp.py).
