### ISSUE TITLE
No meta.json in ref-youtube-vos dataset

### ISSUE THREAD

**Issue by zhuyan129** [wjn922/ReferFormer#20]
Hi, I download and zip the youtube_vos datasets as guided. But there is not the meta.json in data/ref-youtube-vos/train folder and the code need this. What should I do?Thanks.

**Comment by wjn922** [comment]
Hi，

The official website may remove the `meta.json`. We upload the file [here](https://drive.google.com/drive/u/1/folders/1-gKWVtHYXG8FwaeTz5jhc0V8JDozx-84).

**Comment by zhuyan129** [comment]
Thanks. But it seems that I can't download the file, could I get the google drive access?

**Comment by wjn922** [comment]
Sorry for that. It can be accessed now.

**Comment by zhuyan129** [comment]
Thanks a lot!
