### ISSUE TITLE
No train.zip in ref-youtube-vos dataset

### ISSUE THREAD

**Issue by zhuyan129** [wjn922/ReferFormer#21]
Hi, there is no train.zip in the competition's website (https://competitions.codalab.org/competitions/29139#participate-get_data). I can't get training data. Can you share a copy? Thanks.

**Comment by wjn922** [comment]
The Ref-Youtube-VOS train set is the same as Youtube-VOS. Please download it from [https://competitions.codalab.org/competitions/20127#participate-get_data](https://competitions.codalab.org/competitions/20127#participate-get_data).

**Comment by zhuyan129** [comment]
OK, thanks!
