### ISSUE TITLE
About sentence feature

### ISSUE THREAD

**Issue by npmhung** [wjn922/ReferFormer#23]
Hello, the paper states that the sentence feature is obtained by pooling the text features. However, when reading your code, I saw that the sentence feature is actually from the pooler_output of the Roberta model. 
According to this https://huggingface.co/transformers/v2.9.1/model_doc/roberta.html#robertamodel, the pooler_output has different meaning than pooling over the text features. 
Have you tried to actually pool the text features to get the sentence level feature? Is it worse than the current way you are doing?

Thank you

**Comment by wjn922** [comment]
Thanks for your information. At the time we implemented the method, we didn't notice the tutorial and regarded the 'pooled_output' would be the pooling of word features. So we didn't experiment with the actual pooling. But I think the operation is worth a try.
