### ISSUE TITLE
Cannot compile cuda version of MSDeformAttnFunction. 

### ISSUE THREAD

**Issue by subramanya1997** [wjn922/ReferFormer#26]
Hi! I tried to compile MSDeformAttnFunction with cuda 11.5.0 and everytime I compile it break and doesn't recognize the cuda module. Is there any other way I can do it ?

**Comment by wjn922** [comment]
Hi, we works well with the cuda version of 11.1 and 11.3. Would you mind degrading your cuda version?

**Comment by subramanya1997** [comment]
Okay thanks!
