### ISSUE TITLE
Training dataset for Pretrain weight

### ISSUE THREAD

**Issue by zhulinxiaohai** [wjn922/ReferFormer#3]
The training dataset of Pretrain weight is ImageNet or RefCOCO、RefCOCO+ and RefCOCOg , or other？

**Comment by wjn922** [comment]
Hi,

The backbone is ImageNet initialized. And we use the combination of RefCOCO, RefCOCO+ and RefCOCOg for pretraining.

**Comment by zhulinxiaohai** [comment]
ok,thanks for your reply ！
