### ISSUE TITLE
Joint Training Settings

### ISSUE THREAD

**Issue by lszw11** [wjn922/ReferFormer#34]
Thank you for your great work! 
I met a problem when I reproduced the result of your joint train. Do any weights of the backbone network need to be loaded during the joint training e.g. video-swin-b-kinetics400-22k. I observed that there is no option to load any weights in the published joint training script. Thanks!

**Comment by wjn922** [comment]
Thanks for your interest.

Yes, you need to load the imagenet-pretrained backbone weights for joint training. Please download the swin/video-swin backbone weights from their official repos first, and then use the arg `--backbone_pretrained` to specify the weight path. 
https://github.com/wjn922/ReferFormer/blob/9c8f237adc260c512a1c5ecfc7aee81b8282649a/opts.py#L33

**Comment by lszw11** [comment]
Thank you for your reply!
