### ISSUE TITLE
Pretraining on RefCOCO Dataset

### ISSUE THREAD

**Issue by ntuLC** [wjn922/ReferFormer#4]
Hi Jonas,

Thanks for your contribution! I noticed that the work supports pretraining on the refcoco dataset. From the code, it seems that it uses a coco-format refcoco dataset for data loading. Is it possible to provide some information about the pretraining process and the dataset conversion tools for refcoco dataset? Thanks in advance!

**Comment by wjn922** [comment]
Hi,

Thanks for your interest. We plan to release the pretrain guidance this week, please stay tuned.

**Comment by ntuLC** [comment]
Sure. Thanks!
