### ISSUE TITLE
Google Drive Links Deprecated

### ISSUE THREAD

**Issue by DeepRunner** [wjn922/ReferFormer#47]
Kinkdly note that google links deprecated 

1) most of model files in the page [https://github.com/wjn922/ReferFormer](https://github.com/wjn922/ReferFormer)
like [https://drive.google.com/file/d/1g9Dm1vLdwpwSKVtIZzWKPUk2-zK3IbQa/view?usp=sharing](https://drive.google.com/file/d/1g9Dm1vLdwpwSKVtIZzWKPUk2-zK3IbQa/view?usp=sharing)

2) and dataset annotation in the page [https://github.com/wjn922/ReferFormer/blob/main/docs/data.md](https://github.com/wjn922/ReferFormer/blob/main/docs/data.md)
like  [https://drive.google.com/drive/u/0/folders/1daTuACcZUKuzgl0iqzwCfKm_tSISarFl](https://drive.google.com/drive/u/0/folders/1daTuACcZUKuzgl0iqzwCfKm_tSISarFl)

Could you please update them?

**Comment by wjn922** [comment]
Hi, all the model and data links have been updated in README. You can also find them in [OneDrive](https://connecthkuhk-my.sharepoint.com/:f:/g/personal/wjn922_connect_hku_hk/EtfZUb7kD61Alvz7uNAyqvYBDXj1uReuo1HFDVaAftGVcg?e=E1VGpf). Thanks for your patience.
