### ISSUE TITLE
0-5 represents the target?

### ISSUE THREAD

**Issue by longmalongma** [wjn922/ReferFormer#53]
Hi，thank you for your good work. Could you help me answer this question? Thank you.
https://github.com/hkchengrex/Tracking-Anything-with-DEVA/issues/76

**Comment by wjn922** [comment]
<img width="527" alt="image" src="https://github.com/wjn922/ReferFormer/assets/21001460/bcb35cd2-f7da-4949-a751-b4b3d68df68d">

You can see the expressions in meta_expressions.json. For the Ref-Youtube-VOS dataset, every two expressions refer to the same object.

**Comment by longmalongma** [comment]
> <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/21001460/318647345-bcb35cd2-f7da-4949-a751-b4b3d68df68d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzQyNTksIm5iZiI6MTcxMjAzMzk1OSwicGF0aCI6Ii8yMTAwMTQ2MC8zMTg2NDczNDUtYmNiMzVjZDItZjdkYS00OTQ5LWE3NTEtYjRiM2Q2OGRmNjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA0NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNDlmZGMyMGRhMzdjOTQzNDkzYTZjNjY4YTllZjM0N2EyYTY3YTFmNzZhYTk5N2E5YjZkMDgyNDU1MmQ1MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kS9pQq3UuOf-Gl902Zqn25pk85zW85B85nSVY3zrjFo">
> You can see the expressions in meta_expressions.json. For the Ref-Youtube-VOS dataset, every two expressions refer to the same object.

Ok, thanks for your reply. Thanks your great work again!
