### ISSUE TITLE
Where to get the test meta file?

### ISSUE THREAD

**Issue by pvoigtlaender** [wjn922/ReferFormer#8]
Hi,

thanks for releasing the great code!
I understand that there have been some changes in the split of the validation and test set and it seems that also the meta file for the test set is no longer available for download on codalab.
Hence, I get an error in this line: https://github.com/wjn922/ReferFormer/blob/8024da12cc84cf18a34094c51a156f940fe224b4/inference_ytvos.py#L79
What is the best way to deal with this? Maybe you could please share the json meta file?

Best,

Paul

**Comment by wjn922** [comment]
Hi,

Please refer to this issue https://github.com/wjn922/ReferFormer/issues/6 to download the meta files.

Alternatively, you can choose to infer all the 507 videos, and submit the results to the evaluation website.

**Comment by pvoigtlaender** [comment]
Great, thx!
I think all 507 videos might be hard because also the JPEGImages are not there anymore.
But the uploaded json works, thx :)
